<?php

namespace App\Controllers;

use App\Controllers\BaseController;
use App\Models\UserModel;

class UserController extends BaseController
{
    protected $userModel;

    public function __construct()
    {
        // Initialize the UserModel
        // This allows us to interact with the 'users' table in the database
        $this->userModel = new UserModel();
    }

    /**
     * Display the registration form
     * This method shows the registration page to the user
     */
    public function register()
    {
        // Simply load and display the Register view
        return view('Register');
    }

    /**
     * Handle the registration form submission
     * This method processes the form data, validates it, and saves the user
     */
    public function create()
    {
        // Step 1: Define validation rules
        // These rules ensure the data is correct before saving to database
        $validationRules = [
            'name' => [
                'rules' => 'required|min_length[3]|max_length[80]',
                'errors' => [
                    'required' => 'Name is required',
                    'min_length' => 'Name must be at least 3 characters long',
                    'max_length' => 'Name cannot exceed 80 characters'
                ]
            ],
            'email' => [
                'rules' => 'required|valid_email|is_unique[Users.email]',
                'errors' => [
                    'required' => 'Email is required',
                    'valid_email' => 'Please provide a valid email address',
                    'is_unique' => 'This email is already registered'
                ]
            ],
            'password' => [
                'rules' => 'required|min_length[8]',
                'errors' => [
                    'required' => 'Password is required',
                    'min_length' => 'Password must be at least 8 characters long'
                ]
            ],
            'password_confirm' => [
                'rules' => 'required|matches[password]',
                'errors' => [
                    'required' => 'Please confirm your password',
                    'matches' => 'Passwords do not match'
                ]
            ]
        ];

        // Step 2: Validate the input data
        // validate() checks if the submitted data meets our rules
        if (!$this->validate($validationRules)) {
            // If validation fails, redirect back to the form with errors
            // getErrors() returns an array of all validation error messages
            return redirect()->back()
                ->withInput() // Keep the old input values (except password)
                ->with('errors', $this->validator->getErrors());
        }

        // Step 3: Prepare the data for insertion
        // Only get the fields we need (security best practice)
        $data = [
            'name' => $this->request->getPost('name'),
            'email' => $this->request->getPost('email'),
            'password' => $this->request->getPost('password'),
            // Note: 'uid' will be auto-generated by the model's beforeInsert callback
            // Note: 'password' will be auto-hashed by the model's beforeInsert callback
        ];

        // Step 4: Try to insert the user into the database
        try {
            // The insert() method returns the new user's ID if successful
            $userId = $this->userModel->insert($data);

            if ($userId) {
                // Success! Redirect to login page with success message
                return redirect()->to('/login')
                    ->with('success', 'Registration successful! You can now login.');
            } else {
                // If insert failed, get the model's errors
                // This catches database-level validation errors
                return redirect()->back()
                    ->withInput()
                    ->with('errors', $this->userModel->errors());
            }
        } catch (\Exception $e) {
            // Catch any unexpected errors (like database connection issues)
            return redirect()->back()
                ->withInput()
                ->with('errors', ['database' => 'An error occurred. Please try again.' . $e->getMessage()]);
        }
    }

}
